name: netrunner
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.14
  ecdsa: ^0.1.2
  elliptic: ^0.3.11
  hive: ^2.2.3
  hive_generator: ^2.0.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
